### ISSUE TITLE
provide a simplified interface for users directly using ODEProblem and such

### ISSUE THREAD

**Issue by isaacsas** [SciML/SymbolicIndexingInterface.jl#20]
The current doc example shows how to use symbolic indexing when coming from MTK, but it would also be nice if users who directly construct SciML problems had a way to attach names (be they strings / symbols / etc) to indexes in `sol.u` and index with them. 

I see https://github.com/SciML/SymbolicIndexingInterface.jl/blob/master/test/example_test.jl -- is there a possibility of providing a simple convenience function / macro that can do all this for a user who just wants to have a mapping from a variable and/or parameter name encoded in some way to an index in `sol.u` for use in solution indexing and plotting?

**Comment by AayushSabharwal** [comment]
To add names to indexes in `sol.u`, they must be `Symbol`s. This can be done using the `SymbolCache` in this library, by passing it as the `sys` to the relevant SciMLFunction. i.e.

```julia
function f(du, u, p, t)
    # ...
end
odefn = ODEFunction(f; sys = SymbolCache([:x, :y, :z], [:a, :b], :t))
```

If there are no e.g. parameter symbols, that field can be `nothing` (or omitted entirely if there is no independent variable either. However, `SymbolCache`s without any independent variable will be assumed to be time-independent (`is_time_dependent(sys) == false`)

**Comment by isaacsas** [comment]
That's great, thanks for pointing that out! I will use that going forward. Once that is in the docs I think this issue can be closed.

**Comment by AayushSabharwal** [comment]
This is now documented [here](https://docs.sciml.ai/SymbolicIndexingInterface/stable/simple_sii_sys/)
