### ISSUE TITLE
Non-intutive behaviour for `getp` and `setp`

### ISSUE THREAD

**Issue by TorkelE** [SciML/SymbolicIndexingInterface.jl#24]
So, with the latest update you cannot index structures directly for parameters, but instead have to use `getp` and `setp`. I understand that it make sense to split this into several steps for performance reasons, but stuff like:
```
getp(prob, k)(prob)
```
is both messy and confusing to the user. Furthermore, the performance cost (at least for small problems) is incredibly reliable. 

Also, e.g. `getp(oprob, p)` *really* sounds like something that gets you the value of `p` in `prob`. Would it make sense to rename the current ones to something like:
```julia
k_getter = pgetter(prob, k)
k_setter = psetter(prob, k)
```
and then one can do
```julia
k_getter(prob)
k_setter(prob, 1.0)
```

Next, we could have `getp` and `setp!` which simply does what you want:
```julia
getp(prob, k)
setp(prob, k, 1.0)
```

something like this feels like a much more intuitive interface.

An alternative is the version where we permit indexing of `prob.ps` directly, so yo can do
```julia
prob.ps[k] # getp
prob.ps[k] = 1.0 # setp
```

**Comment by AayushSabharwal** [comment]
Closing since https://github.com/SciML/SciMLBase.jl/pull/584 released in https://github.com/SciML/SciMLBase.jl/releases/tag/v2.21.0 enables `.ps[p]` syntax
